import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";

/**
 * Factory so the app and tests can each own their database handle.
 * `location` is a file path or ":memory:".
 */
export function createDb(location: string) {
  const sqlite = new Database(location);
  // Enforce referential integrity (off by default in SQLite).
  sqlite.exec("PRAGMA foreign_keys = ON;");
  if (location !== ":memory:") {
    sqlite.exec("PRAGMA journal_mode = WAL;");
    sqlite.exec("PRAGMA busy_timeout = 5000;");
  }
  const db = drizzle(sqlite);
  return { db, sqlite };
}

/** Applies the SQL migrations generated by `drizzle-kit generate`. */
export function applyMigrations(
  db: ReturnType<typeof createDb>["db"],
  migrationsFolder: string,
) {
  migrate(db, { migrationsFolder });
}

export type DB = ReturnType<typeof createDb>["db"];
export type Sqlite = ReturnType<typeof createDb>["sqlite"];
